#! /bin/sh
#
# INPUT
#	gama.dat
#
# OUTPUT
#	ent.tribe
#

{
	echo "%"
	echo "% 16"
	echo "% ent dat.name"

	head -n20 gama.dat | tail -n16 | 
	sed = | sed 'N;s/\n/ /' | 
	sed -re 's,([A-Z]+),"\1",' 
} >ent.tribe
