#! /usr/bin/perl -w
#
# Create the relationship file from the gama.{pos,neg} file. 
#
# ARGUMENTS
#	$1 	"pos" or "neg"
#
# INPUT
#	gama.$1		The input file
#
# OUTPUT
#	rel.$1		The relationship file
#

use strict;

my $name = $ARGV[0]; 

my $ret = ''; 
my $count = 0; 

open(GAMA, "<gama.$name"); 

my $from = 0; 

while (<GAMA>)
{
    ++ $from; 
    my @weights = split;
    my $to = 0;
    for my $weight (@weights)
    {
	++$to; 
	if ($weight == 1)
	{
	    ++ $count; 
	    $ret .= "$from $to\n"; 
	}
    }
}

close(GAMA) or die;

open(REL,  ">rel.$name"); 

print REL "% sym unweighted\n% $count $from $from\n% ent.tribe ent.tribe\n$ret"; 

close(REL) or die; 

