#! /bin/sh
# 
# -a to allow edge weights
# $1: print that suffix every output line
#

alloww=''

[ "$1" = "-a" ] && alloww=yes && shift

li=0

while read -r row
do
	li="$(( $li + 1 ))"
	lj=0

	for entry in $row
	do
		lj="$(( $lj + 1 ))"

		if [ "$entry" != "0" ]; then 
			[ "$alloww" ] || { 
				echo "$li $lj"; 
				continue; 
			}
			[ "$1" ] && entry="$entry $1" 
			echo "$li $lj $entry"
		fi
	done 
done
