#! /bin/sh

MATRIX="$(./mkmatrix -a <sampson.dat)"

op="-"

for i in 2 3 4 5 6 7 8 9 
do
	start="$(( 1 + $i * 18 ))"
##	echo "start='$start'"

	if [ "$op" = "-" ]; then
		op='+'
	else
		op='-'
	fi

	PART="$(echo "$MATRIX" | tail -n+"$start" | head -n18 | sed -e "s/\([1-9]\)/"$op"\1/g")"
 
	echo "$PART" |

	./mkmatrixtolines -a | 

	# Round values to +1/-1
	sed -e 's/^\([0-9]\{1,\} [0-9]\{1,\} [-+]\)[0-9]\{1,\}$/\1'1'/'

done  | 

sort -n -k1 -k2 

