
out.cosimo:  ActionLog-05-27-jerome1-1.log mk 
	./mk

ActionLog-05-27-jerome1-1.log:  ../own/cosimo/ActionLog-05-27-jerome1-1.zip
	unzip ../own/cosimo/ActionLog-05-27-jerome1-1.zip
	touch ActionLog-05-27-jerome1-1.log
