#! /usr/bin/perl -w
#

use strict;

use Time::Local; 

open(IN, "<data/user_rating.txt"); 

while (<IN>)
{
    /([0-9]+)	([0-9]+)	(1|-1)	([0-9]{4})\/([0-9]{2})\/([0-9]{2})/ or die;

    my $user1 = $1;
    my $user2 = $2;
    my $weight = $3; 
    my $year = $4;
    my $month = $5;
    my $day = $6; 

    my $date = timelocal(0, 0, 0, $day, -1+$month, $year);

    print "$user1 $user2 $weight $date\n"; 
}

close(IN) or die;

