#!/bin/bash

./mkformat tmp.ent.brunson_terrorist_2 >ent.brunson_terrorist_terrorist.organization.name
while read line
do
	org="$(echo $line | cut -d ' ' -f1)"
	val="$(echo $line | cut -d ' ' -f1 --complement)"
	sed -i -re "s/^$org$/$val/" ent.brunson_terrorist_terrorist.organization.name
done <terrorist.map
