#! /bin/sh
#
# Compute the degree distribution of a dataset.
#
# Note:  there are other, more readable ways to compute the degree
# distribution of a dataset.  This is implement to show off that it can
# be done using the shell. 
# 
# INVOCATION
#
#	$1 	'1' or '2':  the column to use (left index or right index)
#	$2	out.* filename
#

<$2 sed '/^\%/d' | cut -f$1 -d ' ' | sort | uniq -c | sort -n | sed 's,^\s*,,' | cut -f1 -d ' ' | uniq -c | sed -re 's,^\s*([0-9]+) ([0-9]+)$,\2 \1,' 
