#! /bin/bash

## THIS IS DEPRECATED !!

#removes multiple edges

awk '!x[$1$2]++' 

# TODO Doesn't this just concatenate $1 and $2, and thus it considers
# some edges as equivalent, even if they are not, such as (12, 3) and
# (1, 23)?  --Jerome
