#! /bin/sh
#
# Extract a unirelational dataset out of a "semantic web" file, i.e., a
# file that is typically named '*.nt'. 
#
# STDIN
#	The semantic web file
#
# STDOUT
#	The unirelational dataset in unipartite network format
#
# ARGUMENTS
#	$1 	The relation to extract; empty to extract all relations
#
# PARAMETERS
#	$FORMAT		(optional) "bip"/"sym"/"asym".  As in the first line of outfiles,
#			defaults to "bip".
#	$WEIGHTS	(optional) As in the first line of outfiles,
#			defaults to POSITIVE
#	$verbose	(optional) Enable verbose mode when non-empty
#

[ "$verbose" ] && exec 4>&2 || exec 4>/dev/null

if [ -z "$FORMAT" ] ; then
    FORMAT=bip
fi

if [ -z "$WEIGHTS" ] ; then
    WEIGHTS=positive
fi

{
    if [ "$1" ]
    then
	escaped="`echo $1 | sed -re 's,/,\\\\/,g'`"
	echo >&4 "ESCAPED='$escaped'"
	sed -E -e  '/^\s*<\S+>\s+'"$escaped"'\s+<\S+>\s+\./!d;s/ '"$escaped"' / /;s,\.\s*$,,' 
    else
	sed -E -e 's,^\s*(<\S+>)\s+\S+\s+(<\S+>)\s+\.\s*,\1 \2,;t;d' 
    fi
} |
{
	../../sh/mkrel --enforce-ignorenonexistant --enforce-edgeweights "$FORMAT" "$WEIGHTS" 
} 
