#!/bin/bash

read folder
echo "Processing folder $folder"


find "../dat/$folder" -type f | egrep '(ent\.|out\.|meta\.)' | while read line
do
 echo "Processing $line"
file="$(basename $line)"
 echo 'Creating symlinks for '$file
 newfile=$(echo $file | sed -re 's/^(ent\.|out\.|meta\.|rel\.)([^_]+)_([^_]+)_[^.]+(.*)?$/\1\2_\3\4/')
ln -s "../dat/$folder/$file" "$newfile"
done 
