#! /bin/sh
#
# STDIN 
#	Contact data in original format as described in README
#
# STDOUT 
#	Data in KONECT format
#

echo '% sym positive'

cut -f 1,2,3 |
sed -E -e 's,	([0-9]+)$,	1 \1,' |
../mkuniq1 
