#! /usr/bin/perl -w

use strict;
use warnings FATAL => 'all';

use Math::Round;

my $i=0;

LINE: while (<STDIN>) {
    chomp;
    s/"//g;
    s/ //g;
    next LINE if /[sS]heet.*/;
    next LINE if /^--.*/;
    my $joke= 0;
    my @v= split(',');
    shift(@v);
    $i++;

    foreach my $val (@v)
    {
	$joke++;
	if ($val =~ /^99\.?[0]*/)
	{ 
	    next; 
	}
	print $i." ".$joke." ";
	printf("%.2f", $val);
	print "\n";
    }
}


