#! /usr/bin/perl -w
#

use strict; 
use Date::Parse;

while (<>)
{
    chomp; 
    
    /^([0-9]+)\|([0-9a-f]+)\|([^|]+)\|([^ |]+)$/
	or die "*** error:  syntax error:  $_";

    my $item = $1;
    my $user = $2;
    my $date = $3;
    my $tag  = $4;

    my $time = str2time($date); 

    print "$user $tag $item $time\n"; 
}
