#! /bin/sh
#
# Create outfile.
#
# PARAMETERS
#	$1	name of dataset
#
# INPUT FILES
#	facebooks-$1.txt
#
# STDOUT
#	The out.* data
#

#
# User IDs already seem to be continuous beginning at one, so we don't
# use mkuniq1. 
#

#
# About a third of a "links" relations have no timestamp.  We map these
# to 0, i.e. these relations are modeled as having happened before other
# relations. 
#

sed <facebook-"$1".txt  -E -e '
s,\\N$$,0,
s,([0-9]+)$,1 \1,
    ' 

