#! /bin/sh
#
# Determine the name of a given language.
#
# PARAMETERS 
#	$lg	Wikipedia language code (with underscores if necessary, no dashes)
#
# STDOUT
#	One line, the English name of the language
#
# STDIN
#	Content of sitematrix.json
#

lg="$(echo $lg | sed -E -e 's,_,-,g')"

ret=$(
sed -E -e 's,\\u200e,,g' |
sed -E -e 's/"name":"[^"]+",//g' |
	ascii2uni -a U -q |
	sed -E -e 's/("localname":"[^"]+"\},)/\1\
/g'  	|
	sed -E -e 's,^.*"code":"'"$lg"'"[^[]*\[[^]]*\][^[]*"localname":"([^"]+)".*$,\1,;t;d'
)

[ "$ret" ] || {
	echo >&2 "*** Error:  Empty name for language '$lg'"
	exit 1
}

printf '%s\n' "$ret"
