#! /usr/bin/perl -w
#
# Generate the interwiki meta file. 
#
# INVOCATION
#	$0 $LANG1 $LANG2
#
# OUTPUT FILE
#	out/meta.wikipedia_interlink-${LANG1}-${LANG2}
#

use warnings; 
use strict; 

## use langs; 

my $lang1= $ARGV[0];
my $lang2= $ARGV[1];

open LANG1, "out/lname.$lang1" or die "$!";
my $name1 = <LANG1>;
chomp $name1;
close(LANG1) or die "$!";

open LANG2, "out/lname.$lang2" or die "$!";
my $name2 = <LANG2>;
chomp $name2;
close(LANG2) or die "$!";

## my %names= langs::get_names();

open(META, ">out/meta.wikipedia_interlink-${lang1}-${lang2}") or die "$!"; 

print META "name: Wikipedia links, $lang1 to $lang2\n";
print META "fullname: Wikipedia links, $lang1 to $lang2\n";
						
print META "code: W${lang1}${lang2}\n";

print META "long-description: This network consists of wikilinks between the $name1 Wikipedia and the $name2 Wikipedia. Nodes in the network are individual articles and each directed edge is one wikilink. Only links in the main namespace are present.\n";

print META "url: http://dumps.wikimedia.org/\n";
print META "category: Hyperlink\n";
print META "description: Article–article wikilink\n";
print META "extr: wikipedia\n";
print META "tags:  #loop, #regenerate\n"; 

close META or die "$!";
