#! /usr/bin/perl -w
#
# Parse the DBLP xml file and output citation data.
# 
# STDIN
#	pipe in dblp.xml
#
# STDOUT
#	one reference per line:  CITING_PAPER CITED_PAPER
#

use strict;

my $lastkey= "";

while (<>) 
{
    if (/<(article|inproceedings|proceedings|book|incollection|phdthesis|masterthesis|www) .*key=\"([^\"]*)\"/)
    {
	$lastkey= $2;
    }
    elsif (/<cite .*>([^<]+)<.*/) 
    {
	my $ref = $1;
	next if $ref eq "...";
	print "cite $lastkey $ref\n";
    }
    elsif (/<author>([^<]+)<.*/) 
    {
	my $author = $1;
	$author =~ s, ,_,g;
	print "author $author $lastkey\n";
    }
}
