#! /bin/sh
#
# Create the "Wikispeedia" dataset.
#
# Since article names can start with '%' due to the URL encoding used,
# we prefix all names with 'X' before calliong sh/mkuniq1, which treats
#

{

<out/wikispeedia_paths-and-graph/paths_unfinished.tsv sed -E -e '
	/^#/d
	/^\s*$/d
	s,^\S+\s+\S+\s+\S+\s+(.*)	\S+	\S+$,\1,
'

<out/wikispeedia_paths-and-graph/paths_finished.tsv sed -E -e '
	/^#/d
	/^\s*$/d
	s,^\S+\s+\S+\s+\S+\s+(.*)	\S+$,\1,
'

} | ./mkpath | sed -E -e 's,^,X,;s,	,	X,' | ../../sh/mkuniq1
