#! /usr/bin/perl
#
# INPUT 
#	petster-data/catster/pals/
#
# OUTPUT 
#	dat-petster/out.petster_orig-cat-friend
#

use strict;
use warnings;

opendir (IN, "petster-data/catster/pals/") or die "$!";
my @filenames = sort readdir(IN);
closedir IN or die "$!";

open F_OUT, ">dat-petster/out.petster_orig-cat-friend" or die "$!";
print F_OUT "% sym unweighted\n";

foreach my $filename(@filenames) {
    
    next if ($filename eq "." || $filename eq ".."); 

    my $path = "petster-data/catster/pals/$filename";
    if (not $filename =~ /^pals_(\d+)\.\d+$/) {
	print STDERR "*** Invalid filename «$path»\n"; 
	exit 1;
    }

    my $cat = $1;
    open F_IN, "<$path" or die "$!";

    while (<F_IN>) {
	my $line = $_;
	    
	while ($line =~ /<a href="\/cats\/(\d+)" target="*_top"*>/gi) {
	    if (-e "petster-data/catster/cats/$1") {
		print F_OUT "$cat\t$1\n";
	    }
	}
    }

    close F_IN or die "$!";
}

close F_OUT or die "$!";
