#! /usr/bin/perl
#
# INPUT 
#	dat-petster/out.petster_orig-catdog-family
#	petster-data/dogster/dogs/
#
# OUTPUT 
#	dat-petster/out.petster_orig-dog-family
#

use strict;
use warnings;

open IN,  "<dat-petster/out.petster_orig-catdog-family" or die "$!";
open OUT, ">dat-petster/out.petster_orig-dog-family"    or die "$!";

while (<IN>) {
    chomp;
    if (! /^\s*([0-9]+)\s+([0-9]+)\s*$/) {
	print OUT "$_\n";
	next
    }

    my $u = $1;
    my $v = $2;

    if ( -e "petster-data/dogster/dogs/$u" &&
	 -e "petster-data/dogster/dogs/$v") {
	print OUT "$_\n";
    }
}

close IN  or die "$!";
close OUT or die "$!";
