%
% Ordered list of all features used in the paper. 
%

function [names] = petster_names_feature()

names = { 'degdiff'; 'friend'; 'cn'; 'jaccard'; ...
          'raceeq'; 'sexeq'; 'coloringeq'; ...
          'latlongeq'; ...
          'birthdaydiff'; ...
          'joinedeq'; ...
          'joineddiff'; ...
          'joinagediff'; ...
          'weightdiff'; ...
          'weighteq' ...
        };
