#! /bin/sh

{
    echo '% bip positive' 

<../own/WebUni/forum_webuni.csv \
sed -re '

# Remove first line
1d 

# Remove spaces in terms
y/ /_/

# Remove end-of-sentence markers
/"xxxooxxx"/d

# Remove empty terms 
/""/d

# Filter 
s/^[0-9]+,"(.[^"]*)",([0-9]+),([0-9]+),[0-9]+,([0-9]+),[0-9]+,[0-9]+$/\3 \1 \2 \4/

' |
../mkuniq ; } >out.webuni

