#! /usr/bin/perl
#
# Create the ratings file. 
#
# INPUT
#	filmtipset/grades.txt
#
# OUTPUT
#	rel.rating	Ratings, with original, non-continuous IDs
#

use warnings;
use strict;

use Date::Parse;

open(GRADES, "<filmtipset/grades.txt") or die $!; 
open(REL, ">rel.rating") or die $!; 

print REL "% bip multiweighted\n"; 

while (<GRADES>)
{
	my ($user, $ratingsText) = /([0-9]+)=(.*)/ 
	    or die "Syntax error:  $_"; 

	my @ratings = split ";", $ratingsText; 

	foreach my $rating (@ratings)
	{
		my ($item, $value, $date) = ($rating =~ /([0-9]+):([0-9]+):(.*)/)
		    or die; 
		
		my $time = str2time($date); 

		print REL "$user\t$item\t$value\t$time\n"; 
	}
}

close(GRADES) or die $!; 
close(REL) or die $!; 
