#! /usr/bin/perl -w

use strict;

while (<STDIN>)
{
    /^\S+\t[^\t]+\t(.*)$/ or 
	die "Invalid input:  $_"; 

    my $tweet = $1; 

    my $f_retweet = ($tweet =~ /\b(rt|retweet|retweeting|♺|via)\s*(:|@)/i ? 1 : 0); 

    my @words = split /\s+/, $tweet; 

    foreach (@words) 
    {
	my $word = lc; 
	$word =~ s/[,.!?:"]+$//; 
	$word =~ s/^["]+//; 
	next if $word eq ""; 
	print "$f_retweet $word\n"; 
    }
}
