#! /usr/bin/perl

use strict;
use warnings;

my $file;
open $file, $ARGV[0] or die $!;
my $file_thread_list;
open $file_thread_list, '>',  "data/thread_list.txt" or die $!;
my $file_page_list;
open $file_page_list, '>', "data/page_list.txt" or die $!;
my $file_table;
open $file_table, '>', "data/table_thread_page.csv" or die $!;

my $page_title;
my $page_id;
my $last_id = -1;

while (<$file>) {
	#$page = $1 if(/<title>([^<]*)<\/title>/);
	#print "$page `'$1'" if(/^==(.*)==$/)

	$page_title = $1 if /^<title>(.+)<\/title>/;
	$page_id = $1 if /^<id>(.+)<\/id>/;

	if (/<\/page>/ and $page_id>$last_id) {
		$last_id = $page_id;
		print $file_page_list "$page_id\t$page_title\n" 
	}

	if(/<thread>.+<\/thread>/) {
		/<id>(.+)<\/id>/;
		my $thread_id = $1;
		/<name>(.+)<\/name>/;
		my $thread_name = $1;
		print $file_thread_list "$thread_id\t$thread_name\n";
		print $file_table "$thread_id\t$page_id\n"
	}
}

close $file or die $!;
close $file_table or die $!;
close $file_page_list or die $!;
close $file_thread_list or die $!;
