#! /bin/sh
#
# Create the training dataset.
#
# INPUT
# 	download/training_set/*		All rating files
# 
# OUTPUT
#	out.training.raw	in matlab format, with holes in the user IDs. 
#

exec 4>out.training.raw

find download/training_set/ -name '*.txt' | 
{
    while read name
    do
      movieid="`echo $name | sed -re 's,^download/training_set/mv_,,;s,\.txt$,,;s,^0*,,'`"
      [ "$movieid" ] || { echo >&2 "*** error:  movieid=»$movieid«, name=»$name«" ; exit 1 ; }
      <$name >&4 sed -re '
/:/d
s|^([0-9]+),([1-5]),([0-9]{4})-([0-9]{2})-([0-9]{2})$|\1 '$movieid' \2 \3\4\5|
' 
    done
}
