
function labels = lkml_labels()

labels = { 'Company (Most Active)'; ...
           'Company (Other)'; ...
           'Hobbyists'; ...
           'Universities'; ...
           'Research Institutions' };
