#! /usr/bin/perl

use strict;
use warnings;

use Time::Local;

my $pmap = {};

open(my $MAPPING,'<','mapping') or die "$!";

while (<$MAPPING>)
{
    chomp;
    /([0-9]+)\s+([0-9]+)/ or die "Invalid mapping";
    $pmap->{$1} = $2;	
}

close($mapping) or die "$!";

LINE: while (<>) {
    chomp;
    /([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)/ or die "Invalid input line"; 

    my $date = "$4 $5";
    my ($year, $mon, $mday, $hour, $min, $sec) = split(/[\s.:-]+/, $date);
    my $time = timelocal($sec, $min, $hour, $mday, $mon - 1, $year);
    my $newpid = $2;
    if (defined $pmap->{$2}) {
	$newpid = $pmap->{$2};
    }
    print "$newpid $3 1 $time\n";
}	

