#! /usr/bin/perl -w
#
# Generate outfile. 
#
# PARAMETERS
#	$wiki	Name of wikimedia site, e.g. "frwiki" or "nlwiktionary"
#
# INPUT
#	tmp/$wiki-latest-stub-meta-history.xml
#
# OUTPUT
#	out/raw.edit-$wiki
#	out/out.edit-$wiki
#	out/ent.edit-$wiki-user
#	out/ent.edit-$wiki-page
#

use strict; 

use Date::Parse;

# Current wiki
my $wiki = $ENV{'wiki'}; 

open(XML, "<tmp/$wiki-latest-stub-meta-history.xml") or die;
open(RAW, ">out/raw.edit-$wiki") or die; 
open(OUT, ">out/out.edit-$wiki") or die; 
open(ENT_PAGE, ">out/ent.edit-$wiki-page") or die; 
open(ENT_USER, ">out/ent.edit-$wiki-user") or die; 

print OUT "% bip positive\n"; 
print ENT_PAGE "%\n%\n% ent dat.string.name\n"; 
print ENT_USER "%\n%\n% ent dat.string.name\n"; 

# Current page name and ID
my $page = "";
my $pageid = 0; 
my $page_nospace;

# Current timestamp
my $timestamp;

# Users
my %users = (); 
my $users_next_id = 1; 

while (<XML>)
{
    if (/^\s+\<title\>(.+)\<\/title\>/) {
	$page = $1; 
	++ $pageid; 

	my $page_esc = $page; 
	$page_esc =~ s,\\,\\\\,g; 
	$page_esc =~ s,",\\",g;

	$page_nospace = $page;
	$page_nospace =~ s,\s,_,g;
	
	print ENT_PAGE "$pageid \"$page_esc\"\n"; 
    }

    if (/^\s+\<timestamp\>(.+)\<\/timestamp\>/) {
	$timestamp = $1;
	$timestamp = str2time($timestamp); 
    }

    if (/^\s+\<username\>(.+)\<\/username\>/) {
	my $username = $1; 
	if (! exists $users{$username}) {
	    $users{$username} = $users_next_id; 

	    my $username_esc = $username;
	    $username_esc =~ s,\\,\\\\,g; 
	    $username_esc =~ s,",\\",g;
	    print ENT_USER "$users_next_id \"$username_esc\"\n"; 

	    ++ $users_next_id;
	}
	my $userid = $users{$username}; 

	my $username_nospace= $username;
	$username_nospace = $username;
	$username_nospace =~ s,\s,_,g;
	
	print RAW "$username_nospace\t$page_nospace\t$timestamp\n"; 
	print OUT "$userid\t$pageid\t1\t$timestamp\n"; 
    }    
}

close(XML) or die; 
close(RAW) or die; 
close(OUT) or die; 
close(ENT_PAGE) or die; 
close(ENT_USER) or die; 
