#! /bin/sh

set -e

echo '% bip weighted'
sed -E -e '
	/`rating`/!d
	/ALTER TABLE `rating`/d
	s/^INSERT INTO `rating` VALUES //
	s/;\s*$//
	s/\),\(/)\
(/g
' |
sed -E -e '
	s/^\([0-9]+,([0-9]+),([0-9]+),([-0-9+.]+),[^,]+,'\''([^'\'']+)'\''.*$/\1	\2	\3	\4/
	t
	d
' |
./convdate |
../../sh/mkuniq
